name: exenv
channels:
  - conda-forge
  - ioam
dependencies:
  - python
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - requests
  - pillow
  - xarray
  - holoviews
  - geoviews
  - datashader
  - cartopy
  - pyproj
